spring:
  datasource:
    url: jdbc:${SPRING_JDBC_DATABASE_CLIENT:postgresql}://${SPRING_JDBC_DATABASE_HOST:localhost}:${SPRING_JDBC_DATABASE_PORT:5432}/${SPRING_JDBC_DATABASE_SCHEMA:healthcare}
    username: ${SPRING_JDBC_DATABASE_USERNAME:spring}
    password: ${SPRING_JDBC_DATABASE_PASSWORD:spring.pwd}
    driver-class-name: ${SPRING_JDBC_DATABASE_DRIVER:org.postgresql.Driver}
  jpa:
    properties:
      hibernate:
        dialect: ${SPRING_JDBC_DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
