spring:
  config:
    import: ${SPRING_CONFIGSERVER_IMPORT:optional:configserver:https://configserver.deiv70.site:8888}
  profiles:
    active: ${ENVIRONMENT:local}
    group:
      local:
        - local_properties
        - local_jdbc
#    include: ${SPRING_PROFILES_INCLUDE:jdbc}
