spring:
  datasource:
    url: jdbc:tc:${SPRING_TESTCONTAINERS_DATABASE_CLIENT:postgresql}:${SPRING_TESTCONTAINERS_DATABASE_CLIENT_VERSION:latest}:///${SPRING_TESTCONTAINERS_DATABASE_SCHEMA:test}?TC_INITSCRIPT=file:${SPRING_TESTCONTAINERS_DATABASE_INITSCRIPT:src/main/resources/schema.sql}
    username: ${SPRING_TESTCONTAINERS_DATABASE_USERNAME:test}
    password: ${SPRING_TESTCONTAINERS_DATABASE_PASSWORD:test}
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    properties:
      hibernate:
        dialect: ${SPRING_TESTCONTAINERS_DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
